import React from 'react';
import InboxView from "../components/Inbox/InboxView";
import {VIEWS} from "../components/Inbox/inbox-constants";
import InboxDownloadModal from "../components/Inbox/InboxDownloadModal";
import InboxDownloadResultView from "../components/Inbox/InboxDownloadResult/InboxDownloadResultView";
import {INITIAL_VALUES} from "../components/Inbox/SearchForm";

export default {
    title: 'Inbox',
};

const results = {
    "invoices": [{
        "description": "City of Stonnington Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 700.00,
        "receivedTime": "2021-03-01T05:38:59.178Z",
        billRef2: "12 Imaginary Place, Cloudville, HVN 0000",
        billRef3: "John Doe",
        billerActorId: 1,
        billerCustomerNumber: "928374",
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 600.00,
        "forwardingStatus": null,
        "invoiceNo": "20201112-9",
        "supplierName": null,
        "billId": 359,
        "installment": "total",
        "documentId": "20201112-9-e7e5a846-3af6-4fa4-9ae8-0c0ffc3f92c2.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "payment-due",
        "contentsType": "summary",
        "id": 214,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/city_of_stonnington.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-9-e7e5a846-3af6-4fa4-9ae8-0c0ffc3f92c2.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": null,
        "billerName": "City of Stonnington",
        "payerActorId": 24
    }, {
        "description": "City of Stonnington Reminder Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 700.00,
        "receivedTime": "2021-03-01T05:38:59.178Z",
        billRef2: "12 Imaginary Place, Cloudville, HVN 0000",
        billRef3: "John Doe",
        billerActorId: 1,
        billerCustomerNumber: "928374",
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 600.00,
        "forwardingStatus": null,
        "invoiceNo": "20201112-9",
        "supplierName": null,
        "billId": 359,
        "installment": "total",
        "documentId": "20201112-9-e7e5a846-3af6-4fa4-9ae8-0c0ffc3f92c2.pdf",
        "documentType": "invoice-reminder",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "payment-due",
        "contentsType": "summary",
        "id": 214,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/city_of_stonnington.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-9-e7e5a846-3af6-4fa4-9ae8-0c0ffc3f92c2.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": null,
        "billerName": "City of Stonnington",
        "payerActorId": 24
    }, {
        "description": "Hornsby Shire Council Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 600.00,
        "receivedTime": "2021-03-01T05:20:48.682Z",
        billRef2: "12 Imaginary Place, Cloudville, HVN 0000",
        billRef3: "John Doe",
        billerActorId: 1,
        billerCustomerNumber: "123456",
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": false,
        "minAmountDue": 500.00,
        "forwardingStatus": null,
        "invoiceNo": "20201112-8",
        "supplierName": null,
        "billId": 358,
        "installment": "total",
        "documentId": "20201112-8-c9be886d-39d7-4731-a412-b2a4041064ce.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "system",
        "status": "paid",
        "contentsType": "summary",
        "id": 213,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/hornsby-shire-council.jpeg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-8-c9be886d-39d7-4731-a412-b2a4041064ce.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": null,
        "billerName": "Hornsby Shire Council",
        "payerActorId": 24
    }, {
        "description": "Camden Council Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 800.00,
        "receivedTime": "2021-03-01T04:48:56.930Z",
        billRef2: "12 Imaginary Place, Cloudville, HVN 0000",
        billRef3: "John Doe",
        billerActorId: 1,
        billerCustomerNumber: "098765",
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 700.00,
        "forwardingStatus": "awaiting-send",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 357,
        "installment": "total",
        "documentId": "20201112-10-71615182-ae06-49cd-9e44-0c1536eade35.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "no-payment-due",
        "contentsType": "summary",
        "id": 212,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/camden_council_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-71615182-ae06-49cd-9e44-0c1536eade35.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": null,
        "billerName": "Camden Council",
        "payerActorId": 24
    }, {
        "description": "Moree Plains Council - Sundry Debtors Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 0.00,
        "receivedTime": "2021-03-01T04:36:34.874Z",
        "billerActorId": 1,
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 0.00,
        "forwardingStatus": "failed",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 356,
        "installment": "total",
        "documentId": "20201112-10-ac85c59e-af77-4d23-b704-c80cce529814.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "no-payment-due",
        "contentsType": "summary",
        "id": 211,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/moree_plains_shire_council_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-ac85c59e-af77-4d23-b704-c80cce529814.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": null,
        "billerName": "Moree Plains Council - Sundry Debtors",
        "payerActorId": 24
    }, {
        "description": "Murrindindi Shire Council Animals Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 800.00,
        "receivedTime": "2021-03-01T04:28:18.766Z",
        "billerActorId": 1,
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 700.00,
        "forwardingStatus": "sent",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 355,
        "installment": "total",
        "documentId": "20201112-10-c628e4ba-e943-46d6-82c6-22e98a339a15.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "payment-due",
        "contentsType": "summary",
        "id": 210,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/murrindindi_shire_council_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-c628e4ba-e943-46d6-82c6-22e98a339a15.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": "scheduled",
        "billerName": "Murrindindi Shire Council Animals",
        "payerActorId": 24
    }, {
        "description": "Payreq Delivery Demo Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 800.00,
        "receivedTime": "2021-03-01T04:18:23.490Z",
        "billerActorId": 1,
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 700.00,
        "forwardingStatus": "send-in-progress",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 354,
        "installment": "total",
        "documentId": "20201112-10-4f19b11e-0bd7-495e-894d-b7ea0727b99e.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "payment-due",
        "contentsType": "summary",
        "id": 209,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/demo_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-4f19b11e-0bd7-495e-894d-b7ea0727b99e.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": "failed",
        "billerName": "Payreq Delivery Demo",
        "payerActorId": 24
    },{
        "description": "Failed Auto Payment later paid manually",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 800.00,
        "receivedTime": "2021-03-01T04:18:23.490Z",
        "billerActorId": 1,
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": 700.00,
        "forwardingStatus": "send-in-progress",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 354,
        "installment": "total",
        "documentId": "20201112-10-4f19b11e-0bd7-495e-894d-b7ea0727b99e.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "paid",
        "contentsType": "summary",
        "id": 209,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/demo_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-4f19b11e-0bd7-495e-894d-b7ea0727b99e.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": "failed",
        "billerName": "Failed Auto Payment later paid manually",
        "payerActorId": 24
    }, {
        "description": "Payreq Delivery Demo Invoice Due 2021-01-22",
        "forwardingField1": null,
        "failedAutoPaymentId": null,
        "amountDue": 800.00,
        "receivedTime": "2021-03-01T04:16:49.608Z",
        "billerActorId": 1,
        "autoPaymentCreatedDate": "2021-03-01T02:35:48Z",
        "paymentDay": "received-date",
        "invoicesForwardingRuleId": null,
        "downloadStatus": true,
        "minAmountDue": null,
        "forwardingStatus": "awaiting-information",
        "invoiceNo": "20201112-10",
        "supplierName": null,
        "billId": 353,
        "installment": "total",
        "documentId": "20201112-10-0c3b6459-84aa-4d0a-a1e0-c351bd6d9856.pdf",
        "documentType": "invoice",
        "receivedBy": "payreq",
        "updatedBy": "emile.raffoul@payreq.com",
        "status": "payment-due",
        "contentsType": "summary",
        "id": 208,
        "debitLimit": 599.00,
        "dueDate": "2021-01-22T00:00:00.000Z",
        "reminderSentDatetime": null,
        "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/demo_logo.jpg",
        "autoPaymentId": 69,
        "currencyCode": "aud",
        "documentHref": "http://localhost:3000/bill-detail?bill-id=20201112-10-0c3b6459-84aa-4d0a-a1e0-c351bd6d9856.pdf",
        "invoiceDetail": null,
        "autoPaymentStatus": "above-limit",
        "billerName": "Payreq Delivery Demo",
        "payerActorId": 24
    }, {
            amountDue: null,
            autoPaymentCreatedDate: null,
            autoPaymentId: null,
            autoPaymentStatus: null,
            billId: 112650,
            billerActorId: 104578,
            billerName: "Payreq Payroll",
            channelPartnerSystemId: null,
            contentsType: "summary",
            currencyCode: "cad",
            debitLimit: null,
            description: "Pay Stub",
            documentHref: "https://test.payreq.com/bill-detail?bill-id=-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/payreq_logo_square.png",
            documentId: "-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            documentType: "payroll",
            downloadStatus: true,
            dueDate: null,
            failedAutoPaymentId: null,
            forwardingField1: null,
            forwardingStatus: null,
            id: 2923,
            installment: null,
            invoiceDetail: null,
            invoiceNo: "20210309112028454",
            invoicesForwardingRuleId: null,
            minAmountDue: null,
            payerActorId: 10809,
            paymentDay: null,
            receivedBy: "payreq",
            receivedTime: "2021-03-09T23:20:28.454Z",
            reminderSentDatetime: null,
            status: "no-payment-due",
            supplierName: null,
            updatedBy: "system"
        },
        {
            billerCustomerNumber: "928374",
            amountDue: null,
            autoPaymentCreatedDate: null,
            autoPaymentId: null,
            autoPaymentStatus: null,
            billId: 112650,
            billerActorId: 104578,
            billerName: "TasWater",
            channelPartnerSystemId: null,
            contentsType: "summary",
            currencyCode: "aud",
            debitLimit: null,
            description: "Letter",
            documentHref: "https://test.payreq.com/bill-detail?bill-id=-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/demo_logo.jpg",
            documentId: "-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            documentType: "letter",
            downloadStatus: true,
            dueDate: null,
            failedAutoPaymentId: null,
            forwardingField1: null,
            forwardingStatus: null,
            id: 2923,
            installment: null,
            invoiceDetail: null,
            invoiceNo: "20210309112028454",
            invoicesForwardingRuleId: null,
            minAmountDue: null,
            payerActorId: 10809,
            paymentDay: null,
            receivedBy: "payreq",
            receivedTime: "2021-03-09T23:20:28.454Z",
            reminderSentDatetime: null,
            status: "no-payment-due",
            supplierName: null,
            updatedBy: "system"
        },
        {
            billerCustomerNumber: "928374",
            amountDue: 335.00,
            autoPaymentCreatedDate: null,
            autoPaymentId: null,
            autoPaymentStatus: null,
            billId: 112650,
            billerActorId: 104578,
            billerName: "SupplierTradingName Ltd.",
            channelPartnerSystemId: null,
            contentsType: "detail",
            currencyCode: "aud",
            debitLimit: null,
            description: "Peppol Credit Note",
            documentHref: "https://test.payreq.com/bill-detail?bill-id=-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            "logoPath": "https://s3-ap-southeast-2.amazonaws.com/testdocs.payreq.com/logos/logo-Peppol-full.png",
            documentId: "-efc80ef4-1a52-47e4-8f69-b7cf2010f7bf.pdf",
            documentType: "peppol-credit-note",
            downloadStatus: true,
            dueDate: null,
            failedAutoPaymentId: null,
            forwardingField1: null,
            forwardingStatus: null,
            id: 2923,
            installment: null,
            invoiceDetail: null,
            invoiceNo: "20210309112028454",
            invoicesForwardingRuleId: null,
            minAmountDue: null,
            payerActorId: 10809,
            paymentDay: null,
            receivedBy: "payreq",
            receivedTime: "2021-03-09T23:20:28.454Z",
            reminderSentDatetime: null,
            status: "no-payment-due",
            supplierName: "SupplierTradingName Ltd.",
            updatedBy: "system"
        }],
    "meta": {
        "total": 178,
        "typeCounts": {"paymentDue": 134, "paid": 41, "noPaymentDue": 1, "downloaded": 144, "all": 178},
        "defaultDateRange": null,
        "incomingEmail": null,
        "showing": [1, 10]
    }
}


export const cardsView = () => (
    <InboxView inboxItems={results.invoices}
               total={results.meta.total}
               typeCounts={{all: 12, downloaded: 2}}
               showing={results.meta.showing}
               searchParams={INITIAL_VALUES}
               handleSearch={() => {
               }}
               view={VIEWS.cards}
               setView={() => {
               }}
               biller={{id: 1, isCompany: false}}
    />
);

export const tableView = () => <InboxView inboxItems={results.invoices}
                                          total={results.meta.total}
                                          typeCounts={{all: 12, downloaded: 2}}
                                          showing={results.meta.showing}
                                          searchParams={INITIAL_VALUES}
                                          handleSearch={() => {
                                          }}
                                          view={VIEWS.table}
                                          setView={() => {
                                          }}
                                          biller={{id: 1, isCompany: false}}
    />
;

export const inboxDownloadModal = () => <InboxDownloadModal billerId={1}
                                                            show={true}
                                                            onCancel={() => {
                                                            }}
                                                            showWarning={false}
                                                            count={178}/>


export const inboxDownloadModalWithWarning = () => <InboxDownloadModal billerId={1}
                                                                       show={true}
                                                                       onCancel={() => {
                                                                       }}
                                                                       showWarning={true}
                                                                       count={178}/>;

const job = {
    "description": "Merged bills ready for download. File: 729.zip",
    "campaignDocumentType": null,
    "billerActorId": 24,
    "mailhouseSystemId": "payreq",
    "startDate": "2021-03-18T00:30:15.031Z",
    "type": "mail-web-download",
    "billLoadType": null,
    "fileHash": null,
    "endDate": "2021-03-18T00:30:18.640Z",
    "campaignInternalReferenceNumber": null,
    "updatedBy": "emile.raffoul@payreq.com",
    "status": "done",
    "result": "453316900471.local.csv/payreq/out/c95cf311-1743-4dd1-b72c-f749ebaee400-5af21c9a-5169-4e77-96c0-14c30477bd26.zip",
    "id": 729,
    "documentLocationId": 1,
    "campaignName": null
}

export const inboxDownloadResult = () => <InboxDownloadResultView job={job}/>;
export const inboxDownloadResultInProgress = () => (
    <InboxDownloadResultView job={
        {
            ...job,
            status: "in-progress",
            description: "Preparing download. You'll receive an email when ready.",
            endDate: null
        }}/>
);
export const inboxDownloadResultError = () => <InboxDownloadResultView job={{...job, status: "error"}}/>;
