http:
  services:
    COMPOSE_PROJECT_NAME-backend:
      loadbalancer:
        servers:
          - url: https://test.payreq.com/
        passHostHeader: false
    COMPOSE_PROJECT_NAME-frontend:
      loadbalancer:
        servers:
          - url: http://frontend/
        passHostHeader: true
    COMPOSE_PROJECT_NAME-frontend-ember:
      loadbalancer:
        servers:
          - url: http://frontend-ember/
        passHostHeader: true
    COMPOSE_PROJECT_NAME-traefik:
      loadbalancer:
        servers:
          - url: http://traefik:8080/
        passHostHeader: true
  routers:
    COMPOSE_PROJECT_NAME-backend:
      rule: (Host(`localhost`) || Host(`go.COMPOSE_PROJECT_NAME.localhost`))
      entrypoints: web
      service: COMPOSE_PROJECT_NAME-backend
      priority: 1
    COMPOSE_PROJECT_NAME-frontend:
      rule: (Host(`localhost`) || Host(`go.COMPOSE_PROJECT_NAME.localhost`)) && PathRegexp(`^(/|/daily-download.*|/error.*|/fastform/.*|/forgot-password.*|/manifest.json|/pay.*|/payreq-ui.*|/portal.*|/sockjs-node.*|/sso.*|/static/.*|/verify/.*|/xero-sso\.js|.*\.hot-update\.js)$`)
      entrypoints: web
      service: COMPOSE_PROJECT_NAME-frontend
      priority: 2
    COMPOSE_PROJECT_NAME-frontend-ember:
      rule: (Host(`localhost`) || Host(`go.COMPOSE_PROJECT_NAME.localhost`)) && PathRegexp(`^(/apple-touch-icon.*|/css/.*|/customer|/favicon.ico|/fonts/.*|/images/.*|/js/.*|/mypay/.*|/opt-out-result/.*|/robots.txt)$`)
      entrypoints: web
      service: COMPOSE_PROJECT_NAME-frontend-ember
      priority: 3
    COMPOSE_PROJECT_NAME-traefik:
      rule: Host(`traefik.COMPOSE_PROJECT_NAME.localhost`)
      entrypoints: web
      service: COMPOSE_PROJECT_NAME-traefik
